name: NPM PR Create
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Checkout version-bump branch
        run: |
          git fetch origin
          git checkout -b version-bump
          git reset --hard origin/main
          git push -f origin version-bump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lerna version
        run: npx lerna version minor --yes --no-private --conventional-commits --create-release github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create PR
        run: |
          git push origin version-bump
          gh pr create --title "Version Bump" --body "Version Bump" --base main --head version-bump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve and merge PR
        run: |
          gh pr merge --admin --auto --squash --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Lerna publish
        run: npx lerna publish from-git --yes --registry https://registry.npmjs.org/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
