name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20] # Define the Node.js versions you want to test against
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Add other setup options as needed

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build
      #todo
      # - name: Test
      #   run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20] # Define the Node.js versions you want to publish with
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Add other setup options as needed

      - name: Install dependencies
        run: npm ci

      - name: Publish packages
        run: |
          # Example using Lerna
          # Replace with your actual publish command using Lerna or other tools
          npx lerna publish from-package --yes --no-private
          # Example using Yarn Workspaces
          # yarn publish --access public

        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
