name: Release
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Set Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Run lerna version
        id: lerna-version
        run: |
          echo "::set-output name=next-version::$(npx lerna version minor --yes --no-private --conventional-commits --create-release=github)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release branch
        run: |
          git checkout -b release-${{ steps.lerna-version.outputs.next-version }}

      - name: Push changes
        run: |
          git push origin release-${{ steps.lerna-version.outputs.next-version }}

      - name: Publish
        run: |
          npx lerna publish from-git --yes --no-private

      - name: Create Pull Request
        run: |
          gh pr create --base main --head release-${{ steps.lerna-version.outputs.next-version }} --title "Release v${{ steps.lerna-version.outputs.next-version }}" --body "Release v${{ steps.lerna-version.outputs.next-version }}" --label release
