name: Node.js Package

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20] # Define the Node.js versions you want to test against
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Add other setup options as needed

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Test
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20] # Define the Node.js versions you want to publish with
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Add other setup options as needed

      - name: Install dependencies
        run: npm ci

      - name: Version packages
        run: npx lerna version minor --yes --conventional-commits --create-release github --no-private
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish packages
        run: |
          npx lerna publish from-package --yes --no-private

        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
